#!/bin/sh


## USERSPACE DAEMONS
#~ sleep 1 && unclutter -root & - MOVED TO /etc/default/unclutter, causes openarena bug
(exec ~/bin/userapps.d.sh)&


## AUTOSTART SOME APPLICATIONS
(sleep 3; exec ~/misc/src/sonata/sonata.py&)&
(sleep 3; exec transmission-gtk&)&
(exec ~/misc/src/gajim/launch.sh)&
(sleep 6; exec urxvtc -name Terminal&)&


#ASK IF USER WANTS FIREFOX TO START (LAUNCH COMMAND FROM MENU)
(zenity --question --width=272 --title "Fluxbox Autostart" --text "Run Firefox?" && exec `grep -vE "^ *#|^ *$|^ *;" .fluxbox/menu|grep firefox|cut -d\{ -f 2|cut -d\} -f 1`)&


# And last but not least we start fluxbox.
exec fluxbox
